

#pragma region SIMON_SETTING

#define SIMON_MAX_WHIP_LEVEL 3

#define SIMON_BLINK_TIME 120

#define SIMON_WALKING_SPEED 0.1f
#define SIMON_ACCEL_WALK_X	0.0005f

#define SIMON_WALKING_STAIR_SPEED 0.045f
#define SIMON_AUTO_WALKING_STAIR_SPEED 0.03f

#define SIMON_HURT_VX 0.1f    
#define SIMON_HURT_VY 0.1f   
#define SIMON_HURT_TIME 500  
#define SIMON_UNTOUCHABLE_TIME 2000 
#define SIMON_INVISIBLE_TIME 5000

#define SIMON_JUMP_SPEED 0.255f

#define SIMON_ATTACK_TIME 450

#define SIMON_GRAVITY -0.001f
#define SIMON_GRAVITY_JUMP -0.00075f

#define SIMON_DEAD_TIME 800

#define SIMON_FLOATING_TIME 150

#define MAX_HEALTH 16
#pragma endregion

#pragma region GHOUL_SETTING

#define GHOUL_WALKING_SPEED	0.03f

#define GHOUL_WIDTH 16
#define GHOUL_HEIGHT 32

#define GHOUL_SPAWN_TIME 5000

#pragma endregion

#pragma region FISHMAN_SETTING

#define FISHMAN_RUN_SPEED 0.02f
#define FISHMAN_JUMP_SPEED 0.5f

#define FISHMAN_WIDTH 16
#define FISHMAN_HEIGHT 32

#define FIREBALL_WIDTH 8
#define FIREBALL_HEIGHT 8

#define FISHMAN_HP 1

#define FISHMAN_ACTIVE_RANGEX 72
#define FISHMAN_ACTIVE_RANGEY 100

#define FISHMAN_ATTACK_TIME 400

#define FISHMAN_ATTACK_COOLDOWN 3000

#define FISHMAN_GRAVITY -0.001f

#define FISHMAN_SPAWN_TIME 5000

#pragma endregion

#pragma region PANTHER_SETTING

#define PANTHER_HP 1

#define PANTHER_WIDTH 32
#define PANTHER_HEIGHT 16

#define PANTHER_RANGE_ACTIVE 64

#define PANTHER_RUN_SPEED 0.15f
#define PANTHER_JUMP_VY 0.2f

#pragma endregion

#pragma region BAT_SETTING

#define BAT_FLYING_SPEED 0.075f
#define BAT_SWING_SPEED 0.05f

#define BAT_RANGE_ACTIVE_MIN 196.0f
#define BAT_RANGE_ACTIVE 360.0f

#define BAT_SWING_COOLDOWN 500

#define BAT_WIDTH 16
#define BAT_HEIGHT 16

#define BAT_HP 1

#define BAT_SPAWN_TIME 7000

#pragma endregion

#pragma region ENEMY_SCORE_SETTING

#define GHOUL_SCORE 100
#define PANTHER_SCORE 200

#pragma endregion

#define PORKCHOP_HEAL_VALUE 6
#define PORKCHOP_WIDTH 16
#define PORKCHOP_HEIGHT 13

#define MAX_TIME 300
#define HOLYCROSS_WIDTH 16
#define HOLYCROSS_HEIGHT 16

#define HOLYWATER_BOTTLE_GRAVITY -0.0002f

#define FLASH_EFFECT_DURATION 400

#define TRANSITION_SCENE_TIME 500

#define SPLASHEFFECT_GRAVITY -0.001f

#define FIREBALL_SPEED 0.05f
#define FIREBALL_DAMAGE 1

#define GHOUL_HP 1

#define NORMAL_ENEMY_ATTACK 2

#define ENEMY_DEAD_TIME 300


#define BIGHEART_HEART_VALUE 5

#define HEART_GRAVITY -0.0075f
#define HEART_MAX_FALLSPEED -0.01f


#define BIG_HEART_WIDTH 12
#define BIG_HEART_HEIGHT 10

#define MORNINGSTAR_WIDTH 16
#define MORNINGSTAR_HEIGHT 16
#define MONEYBAG_SPAWN_DURATION 800

#define MONEYBAG_WIDTH 16
#define MONEYBAG_HEIGHT 16


#define SMALLHEART_HEART_VALUE 1

#define SMALLHEART_SWING_TIME 400

#define SMALLHEART_SWING_SPEED 0.025f


#define HOLYWATERBOTTLE_ITEM_WIDTH 16
#define HOLYWATERBOTTLE_ITEM_HEIGHT 16

#pragma region SIMON_SIZE
#define SIMON_WIDTH 16
#define SIMON_HEIGHT 32

#define SIMON_DIE_WIDTH 30
#define SIMON_DIE_HEIGHT 14

#define SIMON_FALLING_WIDTH 15
#define SIMON_FALLING_HEIGHT 32

#define SIMON_JUMP_WIDTH 15
#define SIMON_JUMP_HEIGHT 32

#define SIMON_HURT_WIDTH 16
#define SIMON_HURT_HEIGHT 28


#define SIMON_IDLE_WIDTH 15
#define SIMON_IDLE_HEIGHT 32

#define SIMON_POWERUP_WIDTH 15
#define SIMON_POWERUP_HEIGHT 32


#define SIMON_SIT_WIDTH 16
#define SIMON_SIT_HEIGHT 24


#define SIMON_SIT_ATTACK_WIDTH 30
#define SIMON_SIT_ATTACK_HEIGHT 24


#define SIMON_STAIR_DOWN_WIDTH 16
#define SIMON_STAIR_DOWN_HEIGHT 32

#define SIMON_STAIR_UP_WIDTH 16
#define SIMON_STAIR_UP_HEIGHT 32

#define SIMON_WALKING_WIDTH 15
#define SIMON_WALKING_HEIGHT 32

#pragma endregion

#define AXE_SPEED 0.0875f
#define AXE_THROW_VY 0.4f

#define AXE_WIDTH 15
#define AXE_HEIGHT 14

#define AXE_GRAVITY -0.001f

#define DAGGER_SPEED 0.1f
#define DAGGER_WIDTH 16
#define DAGGER_HEIGHT 10


#define HOLYWATER_BOTTLE_SPEED 0.05f
#define HOLYWATER_BOTTLE_THROW_VY -0.01f


#define HOLYWATER_BOTTLE_WIDTH 8
#define HOLYWATER_BOTTLE_HEIGHT 4
#define HOLYWATER_BURN_WIDTH 16
#define HOLYWATER_BURN_HEIGHT 13

#define HOLYWATER_BURN_DURATION 1600
#define HOLYWATER_BURN_COOLDOWN 400


#define STAIR_WIDTH 32
#define STAIR_HEIGHT 6


#define BREAKABLE_BRICK_WIDTH 16
#define BREAKABLE_BRICK_HEIGHT 16

#define BREAKABLEOBJCET_DESTROYED_TIME 300

#define CANDLE_WIDTH 8
#define CANDLE_HEIGHT 16

#define TORCH_WIDTH 16
#define TORCH_HEIGHT 32